image: Ubuntu1804  # образ для сборки
stack: node 12       # окружение
branches:
  only:               # ветки, которые будут собираться
    -main           # ветка GitHub
cache: node_modules   # кеширование папки с зависимостями
install:
  -npm install      # команда установки зависимостей
build: off           # отключение сборки (если не требуется)
test_scripts: 
  -npm run lint && npm test  # скрипт тестирования
